export const environment = {
    GOOGLE_CLIENTID : "772453149406-abjsh6ajdo61sr3rcsfqav4u3mj6b5ap.apps.googleusercontent.com",
    BASE_URL : `http://localhost:3000`,
    LOGIN_URL : `http://localhost:3000/api/v1/google/login`,
    PASSWORD_LOGIN : `http://localhost:3000/api/v1/login`,
    LOGOUT : `http://localhost:3000/api/v1/logout`,
    BASE_SUPER_ADMIN_URL : `http://localhost:3000/api/v1/SuperAdmin`,
    ADMIN_URL : `http://localhost:3000/api/v1/Admin`,
    AVAILABILITY_REQUEST_ : `http://localhost:3000/api/v1/SuperAdmin/staffs/availability`,
    GET_ALL_RESPONSE : `http://localhost:3000/api/v1/SuperAdmin/responses`,
    INDIVIDUAL_RESPONSE : `http://localhost:3000/api/v1/SuperAdmin/responses`,
    ALL_STAFF_URL : `http://localhost:3000/api/v1/SuperAdmin/staffs`,
    ACCEPTED_RESPONSE : `http://localhost:3000/api/v1/SuperAdmin/responses/accepted`,
    SLOT :`http://localhost:3000/api/v1/SuperAdmin/slots`,
    STUDENT:`http://localhost:3000/api/v1/Students`,
    STUDENT_SLOT:`http://localhost:3000/api/v1/Students/slots/`,
    STUDENT_BOOKING:`http://localhost:3000/api/v1/Students/slots/`,
    BOOKERS : `http://localhost:3000/api/v1/Admin/students/`,
    STUDENTMARKS : `http://localhost:3000/api/v1/Admin/studentMarks/`,
    STUDENTS_MARKS : `http://localhost:3000/api/v1/Admin/studentMarks`,
    STUDENT_EVENT_RESULT : `http://localhost:3000/api/v1/Students/eventResult/`,
    EVENT_URL : `http://localhost:3000/api/v1/events`,
    CREATE_EVENT:`http://localhost:3000/api/v1/SuperAdmin/events`,
    INFORMATION_STUDENT:`http://localhost:3000/api/v1/Admin/information/students`,
    FILE_UPLOAD : `http://localhost:3000/api/v1/Students/upload`,
    BREAKS : 'http://localhost:3000/api/v1/SuperAdmin/breaks',
    ALLSTUDENTS : 'http://localhost:3000/api/v1/Admin/students',
    DASHBOARD : 'http://localhost:3000/api/v1/SuperAdmin/dashboard',
};
