export const environment = {
    LOGIN_URL : `http://localhost:3000/api/v1/login`,
    BASE_URL : `http://localhost:3000`,
    BASE_SUPERADMIN_URL : `http://localhost:3000/api/v1/SuperAdmin`,
    ADMIN_URL : `http://localhost:3000/api/v1/Admin`,
    AVAILABILITY_REQUEST_ : `http://localhost:3000/api/v1/SuperAdmin/staffs/availability`,
    GETALLREQUEST : `http://localhost:3000/api/v1/SuperAdmin/responses`,
    INDIVIDUALRESPONSE : `http://localhost:3000/api/v1/SuperAdmin/responses`,
    ALLSTAFFURL : `http://localhost:3000/api/v1/SuperAdmin/staffs`,
    ACCEPTEDRESPONSE : `http://localhost:3000/api/v1/SuperAdmin/responses/accepted`,
    SLOT :`http://localhost:3000/api/v1/SuperAdmin/slots`,
    STUDENT:`http://localhost:3000/api/v1/Students`,
    STUDENT_SLOT:`http://localhost:3000/api/v1/Students/slots/`,
    STUDENT_BOOKING:`http://localhost:3000/api/v1/Students/slots/`,
    BOOKERS : `http://localhost:3000/api/v1/Admin/students/`,
    STUDENTMARKS : `http://localhost:3000/api/v1/Admin/studentMarks/`,
    STUDENTSMARKS : `http://localhost:3000/api/v1/Admin/studentMarks`,
    STUDENTEVENTRESULT : `http://localhost:3000/api/v1/Students/eventResult/`,
};
